package com.mg.app_test.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ant.app_greendao.dataBean.ManStudent;
import com.ant.app_greendao.dataBean.Son;
import com.ant.app_greendao.dataBean.Student;
import com.ant.app_greendao.dataBean.Teacher;
import com.ant.app_greendao.dataBean.User;

import com.mg.app_test.dao.ManStudentDao;
import com.mg.app_test.dao.SonDao;
import com.mg.app_test.dao.StudentDao;
import com.mg.app_test.dao.TeacherDao;
import com.mg.app_test.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig manStudentDaoConfig;
    private final DaoConfig sonDaoConfig;
    private final DaoConfig studentDaoConfig;
    private final DaoConfig teacherDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ManStudentDao manStudentDao;
    private final SonDao sonDao;
    private final StudentDao studentDao;
    private final TeacherDao teacherDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        manStudentDaoConfig = daoConfigMap.get(ManStudentDao.class).clone();
        manStudentDaoConfig.initIdentityScope(type);

        sonDaoConfig = daoConfigMap.get(SonDao.class).clone();
        sonDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        teacherDaoConfig = daoConfigMap.get(TeacherDao.class).clone();
        teacherDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        manStudentDao = new ManStudentDao(manStudentDaoConfig, this);
        sonDao = new SonDao(sonDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);
        teacherDao = new TeacherDao(teacherDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(ManStudent.class, manStudentDao);
        registerDao(Son.class, sonDao);
        registerDao(Student.class, studentDao);
        registerDao(Teacher.class, teacherDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        manStudentDaoConfig.clearIdentityScope();
        sonDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
        teacherDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public ManStudentDao getManStudentDao() {
        return manStudentDao;
    }

    public SonDao getSonDao() {
        return sonDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public TeacherDao getTeacherDao() {
        return teacherDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
