package com.mg.app_test.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.ant.app_greendao.dataBean.ManStudent;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MAN_STUDENT".
*/
public class ManStudentDao extends AbstractDao<ManStudent, Void> {

    public static final String TABLENAME = "MAN_STUDENT";

    /**
     * Properties of entity ManStudent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Haha = new Property(0, String.class, "haha", false, "HAHA");
    }


    public ManStudentDao(DaoConfig config) {
        super(config);
    }
    
    public ManStudentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MAN_STUDENT\" (" + //
                "\"HAHA\" TEXT);"); // 0: haha
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MAN_STUDENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ManStudent entity) {
        stmt.clearBindings();
 
        String haha = entity.getHaha();
        if (haha != null) {
            stmt.bindString(1, haha);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ManStudent entity) {
        stmt.clearBindings();
 
        String haha = entity.getHaha();
        if (haha != null) {
            stmt.bindString(1, haha);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public ManStudent readEntity(Cursor cursor, int offset) {
        ManStudent entity = new ManStudent( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // haha
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ManStudent entity, int offset) {
        entity.setHaha(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(ManStudent entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(ManStudent entity) {
        return null;
    }

    @Override
    public boolean hasKey(ManStudent entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
